DROP DATABASE IF EXISTS qualitea;
CREATE DATABASE IF NOT EXISTS qualitea;

USE qualitea;

CREATE TABLE roles (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(50) NOT NULL
);


CREATE TABLE users (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   pseudo VARCHAR(20) NOT NULL UNIQUE ,
   password VARCHAR(150) NOT NULL,
   email VARCHAR(150) NOT NULL UNIQUE ,
   role_id INT(6) UNSIGNED NOT NULL,
   sexe VARCHAR(10) NOT NULL,
   tel INT(10),
   rue VARCHAR(150) NOT NULL ,
   cp INT(5) NOT NULL,
   ville VARCHAR(50) NOT NULL,
   FOREIGN KEY (role_id) REFERENCES roles(id)
);
CREATE TABLE articles (
   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   prix INT(6) NOT NULL,
   stock INT(6),
   img VARCHAR(50) NOT NULL
);

INSERT INTO roles(name) VALUES ("user");
INSERT INTO roles(name) VALUES ("admin");